storage: sqlite #sqlite or mysql
mysql: #if you select mysql above
    hostname: localhost
    username: root
    password: bananas
    database: chestmaster


use_uuid: false #Use UUID or Player Name?
chest_size: 45 #MUST be a multiple of 9!
migrated: true #DO NOT CHANGE, or the plugin will crash/reset
sql_version: 2 #DO NOT CHANGE, or the plugin will crash/reset
networking:
    use_metrics: true #Enable/Disable the Metrics system, please avoid disabling this <3
    use_autoupdate: true #I recommend to keep this active

lang:
    NO_PERMISSION_CHEST_NUMBER: "§cYou cant have this many chests!"
    NO_PERMISSION: "§cAccess Denied"
    INVALID_CHEST_NUMBER: "§6That chest number is invalid"
    ADM_CHEST_USAGE: "§cUse /admchest <player> <chest_number>"
    CHEST_NAME: "§6ChestMaster"