name: ChestMaster
main: com.nunofacha.chestmaster.Main
version: 3.1
commands:
  chest:
    description: Opens a virtual chest
  admchest:
    description: Opens a player virtual chest
  chestreload:
    description: Reload ChestMaster
  chestdebug:
    description: Reload ChestMaster